apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-go
  labels:
    app: cloud-native-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-native-go
  template:
    metadata:
      labels:
        app: cloud-native-go
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: cloud-native-go
        image: your-image:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
